name: brewedcoffee
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.11.0
  crypto: ^3.0.3
  firebase_analytics: ^10.6.1
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  firebase_messaging: ^14.7.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^2.4.1
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  intl: ^0.18.0
  json_annotation: ^4.8.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
