name: brewed_coffee_stacked
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.11.0
  crypto: ^3.0.3
  firebase_analytics: ^10.6.1
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  firebase_in_app_messaging: ^0.7.4+1
  firebase_messaging: ^14.7.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  json_annotation: ^4.8.1
  sign_in_with_apple: ^5.0.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
