name: wiredbrain
description: Project by majid Hajian

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.11.0
  crypto: "^3.0.0"
  firebase_analytics: ^10.6.1
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  firebase_in_app_messaging: ^0.7.4+1
  firebase_messaging: ^14.7.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.6.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  http: ^1.1.0
  json_annotation: ^4.8.1
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
# run flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
